base_url: "http://web.dmi.unict.it/"
approval_group_chatid: null
pages:
  notizie:
    label: "Notizie"
    urls:
      - "notizie/"
    channels:
      - "@channelName" # use channel public name or chatid
